# .cnb.yml
$:
  vscode:
    - docker:
        # build: .ide/Dockerfile
        # 指定开发环境镜像，可以是任意可访问的镜像。
        # 如果 image 指定的镜像中已安装 code-server 代码服务，将使用单容器模式启动开发环境
        # 如下镜像为 CNB 默认开发环境镜像，已安装代码服务，将使用单容器模式启动开发环境
        # 可按需替换为其他镜像
        # image: cnbcool/default-dev-env:latest
        image: docker.cnb.cool/zhenxijs/seo/bolg/nuxt_dev_env:latest
      services:
        - vscode
        - docker
      # env:
        # 配置环境变量，指定首次打开终端时自动执行的命令
        # CNB_WELCOME_CMD: zsh ./.install_claude.sh
      imports:
        - https://cnb.cool/zhenxijs/privet/-/blob/main/github.yml
        - https://cnb.cool/zhenxijs/privet/-/blob/main/ZhiPu.yml

      # 开发环境启动后安装依赖
      runner:
        cpus: 16
      stages:
        - name: 安装环境依赖
          script: npm config set registry https://mirrors.cloud.tencent.com/npm/ && npm install
        - name: 安装Claude Code
          script: zsh /workspace/.ide/claude.sh


# 此定时任务配置在 main 分支下
# 触发时，系统将拉取 main 分支的最新代码进行构建
main:
  # 定时任务配置。用户 A 提交此配置后，任务触发时的执行者即为 A
  "crontab: 0 6 * * *": # 使用 cron 表达式定义执行计划
    - name: 获取AI资讯并提交 # 流水线名称
      docker:
        image: cnbcool/default-dev-env:latest
      imports:
        - https://cnb.cool/zhenxijs/privet/-/blob/main/github.yml
      stages:
        - name: 同仓库到GitHUB
          script: bash /workspace/sync_to_github.sh